### ISSUE TITLE
are RAL hex values correct ?!

### ISSUE THREAD

**Issue by sonicdee** [Korchy/blender-color-matching#1]
hi there, I wonder if the values put out for RAL 
are correct or what is / am I wrong, 
because when I look online there are different values...
for example RAL 6011:

plugin says: #66825B

both sites say: #6c7c59
https://rgb.to/ral/6011
https://www.ralfarbpalette.de/ral-classic/ral-6011-resedagrun

**Comment by sonicdee** [comment]
is there no global correct value ??
here its #68825B
https://www.w3schools.com/colors/colors_ral.asp

and #587246
https://encycolorpedia.de/587246

big confusion

**Comment by Korchy** [comment]
Hello!
Yes, there are very difficult to get a real color value. You need a very clear white room and very high-quality optics for the camera. So it could be a very expensive project to get color values close to the real.
I got a color database from the open internet sources, like in your examples, and colors may differ from real.

**Comment by sonicdee** [comment]
okay, thanks, in fact your hex value fit really good, but I still wonder there is no exact color conversion from RAL to other spaces available
